### PR TITLE
Added lambda role ARN to outputs so it is possible to attach additional policies to the role

### PR DESCRIPTION
**Pull request by Andrey9kin**

### CODE REVIEW

**Comment by Andrey9kin** [comment]
@bamdadd @tobyclemson could you please take a look? Thanks!

**Comment by tobyclemson** [comment]
Hi Andrey,

Are you able to add a test? There are many examples of testing outputs in the other terraform modules on this organisation.

Thanks,
Toby

**Comment by Andrey9kin** [comment]
@tobyclemson sure. do you have those tests running automatically by CI?

**Comment by tobyclemson** [comment]
Yes, they will run on merge via CircleCI. We don't have branch builders though I'm afraid.

It's possible to run the tests locally but a little tricky as there are a few AWS account prerequisites. If you want to be able to run the tests locally, I can give some more detailed instructions.

Let me know.

**Comment by Andrey9kin** [comment]
@tobyclemson I'm not a Ruby person and having a little bit of a hard time to figure out what exactly tests output. Can you give me a hand with that?

About testing locally. It seems like to much hassle to install all the tools only for this single run

**Comment by tobyclemson** [comment]
Hi Andrey, I'll try and take a look over the weekend.

**Comment by tobyclemson** [comment]
I'll merge this now and add a test.

**Comment by tobyclemson** [comment]
Available in [0.7.0](https://registry.terraform.io/modules/infrablocks/api-gateway-lambda-resource/aws/0.7.0)

**Pull request merged**
